apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-qdrant-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.qdrant.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-qdrant
  labels:
    app: qdrant
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount.qdrant }}
  selector:
    matchLabels:
      app: qdrant
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: qdrant
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: qdrant
        image: {{ .Values.images.qdrant.repository }}:{{ .Values.images.qdrant.tag }}
        imagePullPolicy: {{ .Values.images.qdrant.pullPolicy }}
        ports:
        - containerPort: 6333
        - containerPort: 6334
        volumeMounts:
        - name: qdrant-storage
          mountPath: /qdrant/storage
      volumes:
      - name: qdrant-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-qdrant-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-qdrant
  labels:
    app: qdrant
    release: {{ .Release.Name }}
spec:
  selector:
    app: qdrant
    release: {{ .Release.Name }}
  ports:
  - name: http
    port: {{ .Values.service.qdrant.ports.http }}
    targetPort: 6333
  - name: grpc
    port: {{ .Values.service.qdrant.ports.grpc }}
    targetPort: 6334
  type: {{ .Values.service.qdrant.type }}
